#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    username: alumno
    password: $6$qXriE/3l$E4N2ox1m8VsOrEj4CQAW5xyCQMeTYF6kA1ME5n9kpJ5Sm6I3zCT6o.V9SGTe23nNtrTBATd56YXOEkoHFGL0.
  keyboard:
    layout: "es"
    variant: "es"
  locale: "es_ES.UTF-8"
  timezone: "Europe/Madrid"
  storage:
    layout:
      name: direct
    config:
      - type: disk
        id: disk0
        size: 25GB
        device: /dev/sda
  packages:
    - openssh-server
  ssh:
    allow-pw: true
  user-data:
    disable_root: false
